//! System configuration for the AiOS installer.
//!
//! Writes fstab, sets hostname, locale, timezone, keyboard, and user passwords
//! on the installed system. All functions operate on files under the target
//! mount point or run `chroot` commands.

use super::partition::PartitionResult;

/// Write `/etc/fstab` on the installed system.
///
/// Entries are referenced by UUID (not device path) for robustness across
/// hardware changes.
pub fn write_fstab(
    mount_point: &str,
    partition_result: &PartitionResult,
) -> Result<(), String> {
    let content = generate_fstab(
        &partition_result.root_uuid,
        partition_result.efi_uuid.as_deref(),
        &partition_result.swap_uuid,
    );

    let fstab_path = format!("{mount_point}/etc/fstab");
    std::fs::write(&fstab_path, &content)
        .map_err(|e| format!("Failed to write {fstab_path}: {e}"))?;

    Ok(())
}

/// Generate fstab content from partition UUIDs.
///
/// Returns a string suitable for writing to `/etc/fstab`.
pub fn generate_fstab(root_uuid: &str, efi_uuid: Option<&str>, swap_uuid: &str) -> String {
    let mut fstab = String::from(
        "# /etc/fstab - generated by AiOS installer\n\
         # <filesystem>  <mount point>  <type>  <options>  <dump>  <pass>\n",
    );

    fstab.push_str(&format!(
        "UUID={root_uuid}\t/\text4\terrors=remount-ro\t0\t1\n"
    ));

    if let Some(efi) = efi_uuid {
        fstab.push_str(&format!(
            "UUID={efi}\t/boot/efi\tvfat\tumask=0077\t0\t1\n"
        ));
    }

    fstab.push_str(&format!(
        "UUID={swap_uuid}\tnone\tswap\tsw\t0\t0\n"
    ));

    fstab
}

/// Configure the installed system's identity and locale settings.
///
/// Steps (all writing to files under `mount_point` or running `chroot` commands):
/// 1. Set hostname
/// 2. Set `/etc/hosts`
/// 3. Set locale
/// 4. Set timezone
/// 5. Set keyboard layout
/// 6. Set user password (`aios` user)
/// 7. Set root password (same as user)
///
/// # Note
/// Requires root — chroot commands run via `sudo`.
pub fn configure_system(
    mount_point: &str,
    hostname: &str,
    language: &str,
    keyboard: &str,
    timezone: &str,
    master_password: &str,
    progress: impl Fn(&str),
) -> Result<(), String> {
    // 1. Set hostname
    progress("Setting hostname...");
    std::fs::write(format!("{mount_point}/etc/hostname"), format!("{hostname}\n"))
        .map_err(|e| format!("Failed to write hostname: {e}"))?;

    // 2. Set /etc/hosts
    progress("Configuring hosts file...");
    let hosts = format!(
        "127.0.0.1\tlocalhost\n\
         127.0.1.1\t{hostname}\n\
         \n\
         # IPv6\n\
         ::1\tlocalhost ip6-localhost ip6-loopback\n\
         ff02::1\tip6-allnodes\n\
         ff02::2\tip6-allrouters\n"
    );
    std::fs::write(format!("{mount_point}/etc/hosts"), &hosts)
        .map_err(|e| format!("Failed to write hosts: {e}"))?;

    // 3. Set locale
    progress("Configuring locale...");
    let locale = format!("{language}_*.UTF-8");
    let _ = std::process::Command::new("sudo")
        .args([
            "chroot", mount_point, "bash", "-c",
            &format!("sed -i 's/^# *\\({locale}\\)/\\1/' /etc/locale.gen && locale-gen"),
        ])
        .output();

    // Write default locale
    let default_locale = format!("LANG={language}.UTF-8\n");
    // Try common locale codes: language_COUNTRY.UTF-8
    // We use just the language code and let locale-gen figure out the right variant.
    let locale_path = format!("{mount_point}/etc/default/locale");
    std::fs::write(&locale_path, &default_locale).ok();

    // 4. Set timezone
    progress("Setting timezone...");
    let localtime_path = format!("{mount_point}/etc/localtime");
    let _ = std::fs::remove_file(&localtime_path);
    let _ = std::process::Command::new("sudo")
        .args([
            "chroot", mount_point,
            "ln", "-sf",
            &format!("/usr/share/zoneinfo/{timezone}"),
            "/etc/localtime",
        ])
        .output();

    std::fs::write(format!("{mount_point}/etc/timezone"), format!("{timezone}\n")).ok();

    // 5. Set keyboard layout
    progress("Setting keyboard layout...");
    let kb_config = format!(
        "XKBMODEL=\"pc105\"\nXKBLAYOUT=\"{keyboard}\"\nXKBVARIANT=\"\"\nXKBOPTIONS=\"\"\n"
    );
    std::fs::write(format!("{mount_point}/etc/default/keyboard"), &kb_config).ok();

    // 6. Set user password (aios user)
    progress("Setting user password...");
    let _ = std::process::Command::new("sudo")
        .args([
            "chroot", mount_point, "bash", "-c",
            &format!("echo 'aios:{master_password}' | chpasswd"),
        ])
        .output();

    // 7. Set root password (same as user)
    progress("Setting root password...");
    let _ = std::process::Command::new("sudo")
        .args([
            "chroot", mount_point, "bash", "-c",
            &format!("echo 'root:{master_password}' | chpasswd"),
        ])
        .output();

    progress("System configured");
    Ok(())
}

/// Unmount all installer mount points in reverse order.
///
/// Unmounts: efivars, sys, proc, dev, boot/efi, and the root mount.
/// Best-effort — continues even if individual unmounts fail.
pub fn cleanup_mounts(mount_point: &str, is_uefi: bool) -> Result<(), String> {
    let mut errors = Vec::new();

    // Unmount in reverse order of mounting.
    let mut paths = Vec::new();

    // Bind mounts from bootloader step (may already be unmounted).
    if is_uefi {
        paths.push(format!("{mount_point}/sys/firmware/efi/efivars"));
    }
    paths.push(format!("{mount_point}/sys"));
    paths.push(format!("{mount_point}/proc"));
    paths.push(format!("{mount_point}/dev"));

    // EFI partition.
    if is_uefi {
        paths.push(format!("{mount_point}/boot/efi"));
    }

    // Root partition (last).
    paths.push(mount_point.to_string());

    for path in &paths {
        let output = std::process::Command::new("sudo")
            .args(["umount", path])
            .output();

        match output {
            Ok(o) if !o.status.success() => {
                let stderr = String::from_utf8_lossy(&o.stderr);
                // "not mounted" is not a real error during cleanup.
                if !stderr.contains("not mounted") {
                    errors.push(format!("umount {path}: {stderr}"));
                }
            }
            Err(e) => {
                errors.push(format!("umount {path}: {e}"));
            }
            _ => {}
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(format!("Some unmounts failed: {}", errors.join("; ")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fstab_content_uefi() {
        let content = generate_fstab(
            "aaaa-bbbb-cccc-dddd",
            Some("EEEE-FFFF"),
            "1111-2222-3333-4444",
        );

        assert!(content.contains("UUID=aaaa-bbbb-cccc-dddd"));
        assert!(content.contains("/\text4"));
        assert!(content.contains("UUID=EEEE-FFFF"));
        assert!(content.contains("/boot/efi\tvfat"));
        assert!(content.contains("UUID=1111-2222-3333-4444"));
        assert!(content.contains("swap"));
    }

    #[test]
    fn test_fstab_content_bios() {
        let content = generate_fstab(
            "aaaa-bbbb-cccc-dddd",
            None,
            "1111-2222-3333-4444",
        );

        assert!(content.contains("UUID=aaaa-bbbb-cccc-dddd"));
        assert!(content.contains("/\text4"));
        // No EFI line
        assert!(!content.contains("/boot/efi"));
        assert!(content.contains("UUID=1111-2222-3333-4444"));
        assert!(content.contains("swap"));
    }

    #[test]
    fn test_fstab_header() {
        let content = generate_fstab("root-uuid", None, "swap-uuid");
        assert!(content.starts_with("# /etc/fstab"));
    }
}
